### PR TITLE
update to minecraft 1.20.1

### PR DESCRIPTION
**Pull request by Misaka-L**

### CODE REVIEW

**Comment by loudambiance** [comment]
Just updating the gradle.properties to target the newer fabric and mc version, and it compiles for 1.20.2 as well.

**Comment by lilydjwg** [comment]
> Just updating the gradle.properties to target the newer fabric and mc version, and it compiles for 1.20.2 as well.

I tried and got the following error:

```
> Task :compileJava FAILED
/home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:5: error: cannot find symbol
import net.minecraft.client.gui.DrawableHelper;
                               ^
  symbol:   class DrawableHelper
  location: package net.minecraft.client.gui
/home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:13: error: cannot find symbol
import net.minecraft.util.math.Vec3f;
                              ^
  symbol:   class Vec3f
  location: package net.minecraft.util.math
/home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:14: error: cannot find symbol
import net.minecraft.util.math.Matrix4f;
                              ^
  symbol:   class Matrix4f
  location: package net.minecraft.util.math
/home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:17: error: cannot find symbol
public abstract class HudComponent extends DrawableHelper {
                                           ^
  symbol: class DrawableHelper
/home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:111: error: cannot find symbol
  private static void fill(Matrix4f matrix, float x1, float y1, float x2, float y2) {
                           ^
  symbol:   class Matrix4f
  location: class HudComponent
/home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/components/PitchIndicator.java:5: error: cannot find symbol
import net.minecraft.util.math.Vec3f;
                              ^
  symbol:   class Vec3f
  location: package net.minecraft.util.math
6 errors
```

Did I miss some steps?

**Comment by Misaka-L** [comment]
> > Just updating the gradle.properties to target the newer fabric and mc version, and it compiles for 1.20.2 as well.
> 
> I tried and got the following error:
> 
> ```
> > Task :compileJava FAILED
> /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:5: error: cannot find symbol
> import net.minecraft.client.gui.DrawableHelper;
>                                ^
>   symbol:   class DrawableHelper
>   location: package net.minecraft.client.gui
> /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:13: error: cannot find symbol
> import net.minecraft.util.math.Vec3f;
>                               ^
>   symbol:   class Vec3f
>   location: package net.minecraft.util.math
> /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:14: error: cannot find symbol
> import net.minecraft.util.math.Matrix4f;
>                               ^
>   symbol:   class Matrix4f
>   location: package net.minecraft.util.math
> /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:17: error: cannot find symbol
> public abstract class HudComponent extends DrawableHelper {
>                                            ^
>   symbol: class DrawableHelper
> /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:111: error: cannot find symbol
>   private static void fill(Matrix4f matrix, float x1, float y1, float x2, float y2) {
>                            ^
>   symbol:   class Matrix4f
>   location: class HudComponent
> /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/components/PitchIndicator.java:5: error: cannot find symbol
> import net.minecraft.util.math.Vec3f;
>                               ^
>   symbol:   class Vec3f
>   location: package net.minecraft.util.math
> 6 errors
> ```
> 
> Did I miss some steps?

I think loudambiance's words mean you can update to Minecraft 1.20.2 just have to change the `gradle.properties` on my fork....

**Comment by Misaka-L** [comment]
Minecraft 1.20.1 using joml instead of Minecraft's own OpenGL math library. So many render stuff was broken​.

**Comment by lilydjwg** [comment]
Oops, I even didn't realize this was a pull request... It worked, thanks!

**Comment by loudambiance** [comment]
> > > Just updating the gradle.properties to target the newer fabric and mc version, and it compiles for 1.20.2 as well.
> > 
> > 
> > I tried and got the following error:
> > ```
> > > Task :compileJava FAILED
> > /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:5: error: cannot find symbol
> > import net.minecraft.client.gui.DrawableHelper;
> >                                ^
> >   symbol:   class DrawableHelper
> >   location: package net.minecraft.client.gui
> > /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:13: error: cannot find symbol
> > import net.minecraft.util.math.Vec3f;
> >                               ^
> >   symbol:   class Vec3f
> >   location: package net.minecraft.util.math
> > /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:14: error: cannot find symbol
> > import net.minecraft.util.math.Matrix4f;
> >                               ^
> >   symbol:   class Matrix4f
> >   location: package net.minecraft.util.math
> > /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:17: error: cannot find symbol
> > public abstract class HudComponent extends DrawableHelper {
> >                                            ^
> >   symbol: class DrawableHelper
> > /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/HudComponent.java:111: error: cannot find symbol
> >   private static void fill(Matrix4f matrix, float x1, float y1, float x2, float y2) {
> >                            ^
> >   symbol:   class Matrix4f
> >   location: class HudComponent
> > /home/lilydjwg/FlightHud-master/src/main/java/net/torocraft/flighthud/components/PitchIndicator.java:5: error: cannot find symbol
> > import net.minecraft.util.math.Vec3f;
> >                               ^
> >   symbol:   class Vec3f
> >   location: package net.minecraft.util.math
> > 6 errors
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did I miss some steps?
> 
> I think loudambiance's words mean you can update to Minecraft 1.20.2 just have to change the `gradle.properties` on my fork....

That's exactly what I meant, sorry for the confusion.

**Comment by JohnMarley2021** [comment]
Hi, I'm struggling to understand how to implement your modifications to make the mod work on mc 1.20.1. I've never done anything close to coding so I was wondering if you could help me understand how I should proceed to make it work ?
